# Generated by Django 4.2.8 on 2023-12-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baykar_tech_uav_rental', '0002_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='uav',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
