# Generated by Django 4.2.8 on 2023-12-07 12:26

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baykar_tech_uav_rental', '0005_alter_rental_end_date_alter_rental_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='generate_slug', unique=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='generate_slug', unique=True),
        ),
        migrations.AlterField(
            model_name='uav',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='generate_slug', unique=True),
        ),
    ]
